### ISSUE TITLE
Optimization of save/posting

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#173]
- [x] Analyse network usage on save. What is taking the time? How can it be optimised?
- [x] Investigate how to deploy proxy demon. Check serialization of save object. Can everything be serialised at the moment? Option 1: Use Data Store as a queue system and implement a polling demon to check and process the queue?  Option2: Add proxy demon and open a new port.

**Comment by tokland** [comment]
Request on save: [requests-info.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46fa918b368790bd9ca4b64da252b2d86b56357c2301a03f32dfa17de8407a045e5b1cfa145f5712f8f8da2ba7b43c76825e0fffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98b4cc3e83524e28c8e46380c48.txt)

Not related to save, but can be tackled here, the main view (dataset list) response is very big (867K), because it's asking all fields:

`867929 GET /dataSets?fields=*%2CorganisationUnits%5Bid%2Cpath%5D&order=undefined`

**Comment by tokland** [comment]
From the results, I'd say the tasks are:

- [ ] Reduce datasets request on list (ask only used fields).
- [ ] Check repeated requests to `/sharing?type=categoryCombo...`
- [ ] Use /metadata endpoint for sections (if possible)
- [ ] Check if requests to sharing can use /metadata (I think it's not implemented in dhis2-api)

**Comment by tokland** [comment]
Some notes about the proxy save service:

- The current saving code uses d2 models (dataset, project, sections), butit can be serialized, there is already infrastructure for that in d2, check `import { getJSONForProperties } from 'd2/lib/model/helpers/json';`, `getJSONForProperties(model, Object.keys(model.modelDefinition.modelValidations))`.

- web service vs queue: 
  - web service. pros: simple logic, one request to complete all whole operation. cons: authentication (even though we can use easily the dhis2 server to auth the request), external port access must be configured.
  - queue: pros: no new external endpoints created. Cons: complex logic, we need to use the dataStore and userDataStore to save the saving request and to fetch the results (by polling). I've found no infrastructure in dhis2 to have our proxy daemon working, so it probably should be a script (always running or being called periodically from crontab)
