### ISSUE TITLE
Sixth step (Grey out fields)

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#20]
Reuse current interface -> Manage Data Section > Grey out fields
- [x] Sections should be displayed as a drop down list and includes 'All Sections' option
- [x] Implement select all/none for each category option

**Comment by adrianq** [comment]
Doubt:
- [ ] Analyze -> Allow applying for all and not only per section

**Comment by adrianq** [comment]
Updated card description with today's discussion

**Comment by tokland** [comment]
Just a note: this step will take a bit more time than one would expect since the previous step (disaggregation) added on-the-fly category combinations (thus, not yet in the DB) so the associations must be build by hand (categories, categoryOptionCombos ->categoryOptions) and the component changed accordingly.
