### ISSUE TITLE
Testing non-admin users

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#225]
- [x] Jordania
- [x] Latin America
- [x] Iran
- [x] Iraq
- [x] Kenya

(Friday)

**Comment by tokland** [comment]
Applies to all users: They must have a role with authority "See Dataset Configuration" in order to access the app.

- Negar (Jordania):
  
  Problem: Step 1: Trying to add all corecompetencies. Message: "Your user does not belong to the required user roles: JO__dataset_campmanagement, JO__dataset_other"
  Solution: Add those missing roles to user

  Problem. Save successful but warning: Error adding orgUnits to project JOFM1608 (BPRM): {"httpStatus":"Forbidden","httpStatusCode":403,"status":"ERROR","message":"You don't have the proper permissions to update this object."}
  Solution: User must have a rw sharing of that project/categoryCombo ((i.e MERO_Administrators))

  Problem: Save successful but warning: Error adding dataset to userRole JO__dataset_education: {"httpStatus":"Forbidden","httpStatusCode":403,"status":"ERROR","message":"You don't have the proper permissions to update this object."}
  Solution: User must have a rw sharing of that userRole (i.e MERO_Administrators)

- Camilo (Latin America)

  Problem: Step 1: Trying to add all corecompetencies. Message: Your user does not belong to the required user roles: CO__dataset_campmanagement, CO__dataset_education, CO__dataset_foodsecurity, CO__dataset_icla, CO__dataset_other, CO__dataset_shelter, CO__dataset_wash
  Solution: Should have 2 underscore, fix wrong user Role Names: CO_dataset_education CO_dataset_emergency CO_dataset_GBV CO_dataset_icla CO_dataset_refugee CO_dataset_ucm GL_dataset_beneficiariesCC GL_dataset_beneficiariesProject GL_dataset_beneficiariesTotal GL_dataset_mandatory IR_dataset_advocacy PD_dataset_CM PS_dataset_CM (UDOC) UA_dataset_education UA_dataset_emergency UA_dataset_foodsecurity UA_dataset_GBV UA_dataset_icla UA_dataset_refugee UA_dataset_shelter UA_dataset_wash

  Problem/Solution: Likewise Negar, needs rw sharing for the associated project: COFE1605 (ECHO)

- Shanmugapriyah (Iraq)

Save with warnings:

- User role does no exist: IQ__dataset_campmanagement
- Error adding dataset to userRole IQ__dataset_other: {"httpStatus":"Forbidden","httpStatusCode":403,"status":"ERROR","message":"You don't have the proper permissions to update this object."}

Note that there is no problem when updating associated project IQFM1604 (BPRM) because it has sharing read-write with IQ_Administrators (while others administrators are read-only)

- Laurence (Iran)

- Error adding orgUnits to project IRFE1604 (ECHO): {"httpStatus":"Forbidden","httpStatusCode":403,"status":"ERROR","message":"You don't have the proper permissions to update this object."}
- User role does no exist: IR__dataset_campmanagement

- Thomas (Kenya)

  Problem: On save: "User `Thomas[e1VBW7nr2eG] (User)` is not allowed to create objects of type KEFA1701 (NMFA (HUM)) [tUrlIulbZ1L] (DataSet).",
  Solution: User is missing authority "Add/Update private Data set" that user Role "GL_CountryAdmin". Other user belong to that user Role.

**Comment by adrianq** [comment]
I am closing this one but [mental note] before releasing or creating any major PR we should give it a try with a few of these users at least!
