### ISSUE TITLE
Wrong data in analytics

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dataset-configuration#354]
Wrong data in analytics due to duplicated uids for dataelement/indicators:

indicator_uids="XMRmqF9reP5 UzT7DSkkbxH ZDONOAJJNBV wFrRdK9XyIM"

- [x] Prepare shell migration script

**Comment by tokland** [comment]
https://raw.githubusercontent.com/EyeSeeTea/dataset-configuration/feature/fix-duplicated-uids-script/scripts/fix-duplicated-uids.sh

Tested in http://dev.eyeseetea.com:8080

**Comment by adrianq** [comment]
We have implemented the script to fix the error with the duplicated DEs/Indicator. We have finally implemented a shell script instead of a SQL script as the API provided a safer way for changing this.  The command to run the script:
bash fix-duplicated-uids.sh https://admin:district@gors.nrc.no => Changing admin:district with a superuser username and password
This script requires the following dependencies curl, jq.It would be very convenient if they create a back-up of the database before applying the attached script.

Anyway, it would be better if you ask BAO to run it in your dev server (staging or latest), double check everything is fixed/nothing is broken and then you ask them to run it in prod. The script basically changes the uid of the indicator and then substitute in the custom forms of the dataset the old indicator id with the new indicator id. Therefore, you should check:
- Data entry for the problematic datasets should be working fine
- Pivot table after running the analytics should be working fine
- You should be able to create a new dataset with the DC app using the four problematic DEs/Indicators.
