### ISSUE TITLE
Review user error

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#382]
https://github.com/EyeSeeTea/dataset-configuration-blessed/issues/171

**Comment by tokland** [comment]
The sharings for this dataset are wrong. Check an example of normal sharing of similar datasets:

https://PROSERVER/api/sharing?type=dataSet&id=x802DwRKB86
https://PROSERVER/api/sharing?type=dataSet&id=oe2aUZmou1t

vs the dataset that cannot be saved:

https://PROSERVER/api/sharing?type=dataSet&id=edQvobvlQTh

A dataset should belong to COUNTRY_Administrators (here: KE_Administrators), but this one only has the group GL_GlobalAdministrator. So a non-global-administrator user can read but not update the dataset. The error message is a bit cryptic because the dataset obviously exist, but cannot find it when internally filters by writable datasets.
