### ISSUE TITLE
Data Element Unique constrain error

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#92]
When creating datasets on dataset-configuration sometimes we something hit a response from the server like this:

> duplicate key value violates unique constraint  "dataelement_operand_unique_key" Detail: Key (dataelementid, categoryoptioncomboid)=(1627, 1596) already exists

**Comment by tokland** [comment]
I didn't understand why this constraint even existed, the relationship de/coc should not be unique (section/de/coc is unique), otherwise we would not be able to grey the same data elements in different datasets. And that's indeed what happens if you try in NRC databases.

I've found the confirmation in dhis2-users:

https://lists.launchpad.net/dhis2-users/msg11683.html

> this was a bug that was fixed in 2.24. The problem is the uniqueness constraint on data element + option combo which simply should not be there: dataelement_operand_unique_key

---
So I've removed the constraint in dev.est. Note that *this should also be done in production NRC servers*. 

Steps: 

- Check if the constraint is there:

```
$ sudo -u postgres pg_dump dhis226nrc | grep -B1 "CONSTRAINT dataelement_operand_unique_key" 
ALTER TABLE ONLY dataelementoperand
    ADD CONSTRAINT dataelement_operand_unique_key UNIQUE (dataelementid, categoryoptioncomboid);
```

- To remove the constraint:
```
$ echo "ALTER TABLE dataelementoperand DROP CONSTRAINT dataelement_operand_unique_key;" | sudo -u postgres psql dhis226nrc
```

**Comment by adrianq** [comment]
Ok, so the only thing we have to do about this is to update their production database. No code change is needed, correct?

I am assigning this card to me and will keep it open until we are sure the database is 'fixed'

**Comment by tokland** [comment]
Right, there is no code involved, just run the `ALTER TABLE ...` command in the production DB.
